development:
  clients:
    default:
      database: zips_development
      hosts:
        - localhost:27017
      options:

  options:

test:
  clients:
    default:
      database: zips_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      url: <%= ENV['MONGOLAB_URI'] %>
      options:
        connect_timeout: 15
